parser: babel-eslint
extends: airbnb
rules:
  comma-dangle: [2, 'never']
  no-plusplus: 0
  no-param-reassign: 0
  no-console: 0
  no-mixed-operators: 0
  consistent-return: 0
  no-use-before-define: [2, {functions: false}]
